site_name: Tani Memo

# Repository
repo_name: wiki
repo_url: https://github.com/tanikento/wiki

# Configuration
theme:
  name: 'material'
  language: 'ja'
  feature:
    tabs: true
  palette:
    primary: 'brown'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# 日本語検索設定
extra:
  search:
    language: 'jp'

extra_css:
    - "//fonts.googleapis.com/earlyaccess/notosansjp.css"
    - "//fonts.googleapis.com/css?family=Open+Sans:600,800"
    - "css/custom.css"

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - def_list
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.mark
  - codehilite:
      linenums: true
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
